/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.techspy.bookratingsystem.view;

import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;
import com.techspy.bookratingsystem.controler.IResultsController;
import com.techspy.bookratingsystem.model.NavigationMessage;

/**
 *
 * @author drew
 */
public class PageNavigation extends javax.swing.JPanel {

    /**
     * Creates new form PageNavigation
     */
    public PageNavigation() {
        initComponents();
        Main.injector.getInstance(EventBus.class).register(this);
        prevBt.setEnabled(false);
        IResultsController res = Main.injector.getInstance(IResultsController.class);
        jLabel1.setText("Page: " + res.getCurrentPage() + " of " + res.getNumPages());
    }
    
    
    @Subscribe public void updateResults(IResultsController results) {
        IResultsController res = Main.injector.getInstance(IResultsController.class);
        if (res.hasPrevPage())
        {
            prevBt.setEnabled(true);
        }else {
             prevBt.setEnabled(false);
        }
        
        if (!res.hasNextPage()) {
            nextBt.setEnabled(false);
        }else {
            nextBt.setEnabled(true);
        }
        jLabel1.setText("Page: " + (res.getCurrentPage() + 1) + " of " + res.getNumPages());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prevBt = new javax.swing.JButton();
        nextBt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        prevBt.setText("<");
        prevBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevBtActionPerformed(evt);
            }
        });

        nextBt.setText(">");
        nextBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtActionPerformed(evt);
            }
        });

        jLabel1.setText("Displaying: 4 of 15");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prevBt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextBt)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prevBt)
                    .addComponent(nextBt)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nextBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtActionPerformed
        // TODO add your handling code here:
        Main.injector.getInstance(EventBus.class).post(new NavigationMessage(true));
        IResultsController res = Main.injector.getInstance(IResultsController.class);
        if (res.hasPrevPage())
        {
            prevBt.setEnabled(true);
        }else {
             prevBt.setEnabled(false);
        }
        
        if (!res.hasNextPage()) {
            nextBt.setEnabled(false);
        }else {
            nextBt.setEnabled(true);
        }
        jLabel1.setText("Page: " + res.getCurrentPage() + " of " + res.getNumPages());
    }//GEN-LAST:event_nextBtActionPerformed

    private void prevBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevBtActionPerformed
        // TODO add your handling code here:
        Main.injector.getInstance(EventBus.class).post(new NavigationMessage(false));
        IResultsController res = Main.injector.getInstance(IResultsController.class);
         if (res.hasPrevPage())
        {
            prevBt.setEnabled(true);
        }else {
             prevBt.setEnabled(false);
        }
        
        if (!res.hasNextPage()) {
            nextBt.setEnabled(false);
        } else {
            nextBt.setEnabled(true);
        }
        jLabel1.setText("Page: " + res.getCurrentPage() + " of " + res.getNumPages());
    }//GEN-LAST:event_prevBtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nextBt;
    private javax.swing.JButton prevBt;
    // End of variables declaration//GEN-END:variables
}
