/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.techspy.bookratingsystem.view;

import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;
import com.techspy.bookratingsystem.controler.IUserController;
import com.techspy.bookratingsystem.controler.impl.UserController;
import com.techspy.bookratingsystem.model.User;
import java.awt.CardLayout;

/**
 *
 * @author drew
 */
public class Profile extends javax.swing.JPanel {

    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
        Main.injector.getInstance(EventBus.class).register(this);// register this to receive events
    }

    @Subscribe public void processLogin(IUserController user) {
        System.out.println(user.getUsername());
        //login1.setVisible(false);
        if (user.isLoggedOn())
            ((CardLayout)jPanel1.getLayout()).show(jPanel1, "card3");
        else
            ((CardLayout)jPanel1.getLayout()).show(jPanel1, "card2");
        // set the profile to be visible also make that subscribe to the user
        // so that it can set up the username
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        login1 = new com.techspy.bookratingsystem.view.Login();
        userProfile1 = new com.techspy.bookratingsystem.view.UserProfile();

        jLabel1.setText("<html><h1><u>Profile</u></h1></html>");
        jLabel1.setToolTipText("");

        jPanel1.setLayout(new java.awt.CardLayout());

        login1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(login1, "card2");
        jPanel1.add(userProfile1, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private com.techspy.bookratingsystem.view.Login login1;
    private com.techspy.bookratingsystem.view.UserProfile userProfile1;
    // End of variables declaration//GEN-END:variables
}
