/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.techspy.bookratingsystem.view;

import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;
import com.techspy.bookratingsystem.controler.IResultsController;
import com.techspy.bookratingsystem.controler.ISearchController;
import com.techspy.bookratingsystem.model.NavigationMessage;
import com.techspy.bookratingsystem.model.RatingChangedMessage;
import com.techspy.bookratingsystem.model.Result;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author drew
 */
public class ResultsPanel extends javax.swing.JPanel {

    List<ResultPanel> resultViews;
    /**
     * Creates new form ResultsPanel
     */
    public ResultsPanel() {
        initComponents();
        Main.injector.getInstance(EventBus.class).register(this);
        resultViews = new ArrayList<ResultPanel>();
        resultViews.add(resultPanel1);
        resultViews.add(resultPanel2);
        resultViews.add(resultPanel3);
        resultViews.add(resultPanel4);
        resultViews.add(resultPanel5);
        hideResults();
        Main.injector.getInstance(ISearchController.class).setTitle("").search();
    }

    /**
     * This gets called when the user has hit the search button
     * @param results 
     */
    @Subscribe public void updateResults(IResultsController results) {
        // first clear the current results
        System.out.println("Updating results in Results Panel");
        hideResults();
        int i = 0;
        // then update them and show them as you go along
        
        for(Result res : results.getNextResultPage()) {
            System.out.println(res);
            resultViews.get(i).setResult(res);
            resultViews.get(i).setVisible(true);
            i++;
        }
        
        this.repaint();
        
    }
    
    @Subscribe public void processNav(NavigationMessage message) {
        if (message.isNextPage()) {
            updateResults(Main.injector.getInstance(IResultsController.class));
        } else {
            IResultsController results = Main.injector.getInstance(IResultsController.class);
            hideResults();
            int i = 0;
            // then update them and show them as you go along

            
            for(Result res : results.getPrevResultPage()) {
                System.out.println(res);
                resultViews.get(i).setResult(res);
                resultViews.get(i).setVisible(true);
                i++;
            }

            this.repaint();
        }
    }

    
    private void hideResults() {
        for (ResultPanel res : resultViews) {
            res.setVisible(false);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultPanel1 = new com.techspy.bookratingsystem.view.ResultPanel();
        resultPanel2 = new com.techspy.bookratingsystem.view.ResultPanel();
        resultPanel3 = new com.techspy.bookratingsystem.view.ResultPanel();
        resultPanel4 = new com.techspy.bookratingsystem.view.ResultPanel();
        resultPanel5 = new com.techspy.bookratingsystem.view.ResultPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.techspy.bookratingsystem.view.ResultPanel resultPanel1;
    private com.techspy.bookratingsystem.view.ResultPanel resultPanel2;
    private com.techspy.bookratingsystem.view.ResultPanel resultPanel3;
    private com.techspy.bookratingsystem.view.ResultPanel resultPanel4;
    private com.techspy.bookratingsystem.view.ResultPanel resultPanel5;
    // End of variables declaration//GEN-END:variables
}
