/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.techspy.bookratingsystem.view;

import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;
import com.techspy.bookratingsystem.model.Textbook;
import java.awt.GridLayout;

/**
 *
 * @author drew
 */
public class UserRatedPane extends javax.swing.JPanel {

    /**
     * Creates new form UserRatedPane
     */
    public UserRatedPane() {
        initComponents();
        Main.injector.getInstance(EventBus.class).register(this);// register this to receive events
    }

    @Subscribe public void updateRating(Textbook title) {
        System.out.println("User profile is updating ratings");
        userRatedPanel.setLayout(new GridLayout(5, 1));
        userRatedPanel.add(new UserRated());
        userRatedPanel.add(new UserRated());
        userRatedPanel.add(new UserRated());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userRatedPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout userRatedPanelLayout = new javax.swing.GroupLayout(userRatedPanel);
        userRatedPanel.setLayout(userRatedPanelLayout);
        userRatedPanelLayout.setHorizontalGroup(
            userRatedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        userRatedPanelLayout.setVerticalGroup(
            userRatedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(userRatedPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel userRatedPanel;
    // End of variables declaration//GEN-END:variables
}
