/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.techspy.bookratingsystem.view;

import com.techspy.bookratingsystem.controler.IUserController;
import com.techspy.bookratingsystem.model.RatingEnum;
import com.techspy.bookratingsystem.model.RatingValue;
import com.techspy.bookratingsystem.model.Textbook;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author drew
 */
public class UserRated extends javax.swing.JPanel {

    private Map<RatingEnum, StarRater> ratings;
    /**
     * Creates new form UserRated
     */
    public UserRated() {
        initComponents();
        ratings = new EnumMap<RatingEnum, StarRater>(RatingEnum.class);
        ratings.put(RatingEnum.HELPFUL, helpfulRating);
        ratings.put(RatingEnum.CLARITY, clarityRating);
        ratings.put(RatingEnum.EASINESS, easinessRating);
    }

    public void updateRating(Textbook book) {
        IUserController uc = Main.injector.getInstance(IUserController.class);
        List<RatingValue> rate = uc.getRatings(book);
        titleBt.setText(book.getTitle());
        for (RatingValue val : rate) {
            ratings.get(val.getRatingCategory()).setSelection(val.getTotal());
            System.err.println(val.getRatingCategory() + " " + ratings.get(val.getRatingCategory()).getSelection());
            //ratings.get(val.getRatingCategory()).repaint();
        }
        System.out.println("Updating the rating");
        revalidate();
        invalidate();
        repaint();
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpfulRating = new com.techspy.bookratingsystem.view.StarRater();
        clarityRating = new com.techspy.bookratingsystem.view.StarRater();
        easinessRating = new com.techspy.bookratingsystem.view.StarRater();
        titleBt = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();

        titleBt.setText("jLabel1");

        deleteButton.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleBt)
                .addGap(86, 86, 86)
                .addComponent(helpfulRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clarityRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(easinessRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(helpfulRating, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clarityRating, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(easinessRating, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleBt)
                        .addContainerGap())))
            .addComponent(deleteButton)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.techspy.bookratingsystem.view.StarRater clarityRating;
    private javax.swing.JButton deleteButton;
    private com.techspy.bookratingsystem.view.StarRater easinessRating;
    private com.techspy.bookratingsystem.view.StarRater helpfulRating;
    private javax.swing.JLabel titleBt;
    // End of variables declaration//GEN-END:variables
}
